[package]
name = "generated"
version = "2.1.0"
edition = "2021"
authors = ["Sol2Ink"]

[dependencies]
ink = { version = "~4.1.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
openbrush = { git = "https://github.com/Brushfam/openbrush-contracts", tag = "3.1.0", default-features = false, features = [] }


[lib]
name = "generated"
path = "lib.rs"

[features]
default = ["std"]
std = [
"ink/std",
"scale/std",
"scale-info/std",
"openbrush/std",
]

